/*
 * ./LINUX-GNU/EN/RS/FMSG_REG.C , 2024/05/29
 * ---------------------------------------------------------------------------
 * Do not modify this file. It is automatically generated by MSGBIND from
 * ./RESOURCE/RESOURCE.TXT.
 * To rebuild the language resources, run MSGBIND.
 *
 */

#include "bindings.h"
#include "environ.h"
#include "arjtypes.h"

char M_CANTOPEN[]="Can't open file: %s";
char M_CANTREAD[]="Can't read file: %s";
char M_CANT_SEEK[]="Can't seek file: %s";
char M_CANT_WRITE[]="Can't write file: %s";
char M_REG_TOTALS[]="A total of %d programs were successfully stamped.\n";
char M_REG_FAILED[]="No programs were successfully register-stamped.\n";
char M_REGISTER_BANNER[]="REGISTER version 2.78.02, Copyright (c) 1999-2004 ARJ Software Russia\n";
char M_PATCH_NOT_FOUND[]="Patch not found";
char M_REGISTER_STAMPED[]="%s register stamped.\n";
char M_VERIFY_REGISTRATION[]="Verify your registration by executing %s.\n";
char M_MISSING_REG_FILE[]="Missing REGISTER.DAT file.\n";
char M_REGISTER_HELP[]="Usage: REGISTER program_name  OR  REGISTER -arj  OR  REGISTER -arj32\n       -arj    registers all ARJ for Linux programs in the current\n               directory\n       -arj32  registers all ARJ32 (supplied by ARJ Software, Inc.) programs\n               in the current directory\n";
char M_IMPROPER_REG_FMT[]="Improper REGISTER.DAT format.\nFormat must be one line of eight numbers and one text string.\n";

