/*
 * ./LINUX-GNU/EN/RS/FMSG_SFJ.C , 2024/05/29
 * ---------------------------------------------------------------------------
 * Do not modify this file. It is automatically generated by MSGBIND from
 * ./RESOURCE/RESOURCE.TXT.
 * To rebuild the language resources, run MSGBIND.
 *
 */

#include "bindings.h"
#include "environ.h"
#include "arjtypes.h"

char M_BAD_HEADER[]="Bad archive header";
char M_BADTABLE[]="Bad file data";
char M_CANTREAD[]="Can't read file!  Damaged file?";
char M_DISK_FULL[]="Can't write file!  Disk full?";
char M_ARJSFX_BANNER[]="ARJSFXJR 3.10 - ARJ Archive Self-Extractor.\nCopyright (c) 1998-2002 ARJ Software Russia. All Rights Reserved.\n";
char M_HEADER_CRC_ERROR[]="Header data error!";
char M_SFXJR_TICKER[]=".";
char M_VD_SPACE[]=" ";
char M_SKIPPED[]="Skipped ";
char M_FILE_EXISTS[]="File already exists. ";
char M_CANTOPEN_F[]="Can't open file. ";
char M_EXTRACTING[]="Extracting ";
char M_OK[]=" OK";
char M_CRC_ERROR[]=" Data error!";
char M_INVALID_SWITCH[]="Bad parameter";
char M_CANTOPEN[]="Can't open ";
char M_PROCESSING_ARCHIVE[]="Processing archive: ";
char M_EXTRACTED[]="Extracted ";
char M_FILES[]=" file(s)";
char M_BREAK_SIGNALED[]="Ctl Break!\n";
char M_FOUND_ERRORS[]="Found error(s)!";

