/*
 * ./LINUX-GNU/EN/RS/FMSG_SFX.C , 2024/05/29
 * ---------------------------------------------------------------------------
 * Do not modify this file. It is automatically generated by MSGBIND from
 * ./RESOURCE/RESOURCE.TXT.
 * To rebuild the language resources, run MSGBIND.
 *
 */

#include "bindings.h"
#include "environ.h"
#include "arjtypes.h"

char M_VALID_ENVELOPE[]="Valid envelope!\n";
char M_VERIFYING_ARJSEC[]="*** Verifying ARJ-SECURITY envelope ... ";
char M_BREAK_SIGNALED[]="\nBreak signaled!\n";
char M_SIGTERM[]="\nOperating system has requested program termination\n";
char M_CANTOPEN[]="Can't open %s";
char M_CANT_MKDIR[]="Can't make directory %s\n";
char M_QUERY_CREATE_DIR[]="%s, Create this directory? ";
char M_FOUND_N_ERRORS[]="Found %5d error(s)!";
char M_VLIST_P1[]="Rev/Host OS  ";
char M_LIST_P1[]="Filename     ";
char M_NO[]="NO";
char M_OUT_OF_MEMORY[]="Out of memory";
char M_QUERY_OVERWRITE[]="Overwrite? ";
char M_PROCESSING_ARCHIVE[]="Processing archive: %s\n";
char M_QUIT[]="QUIT";
char M_N_BYTES[]="%10ld bytes, ";
char M_SKIPPED[]="Skipped %s\n";
char M_YES[]="YES";
char M_REPLIES_HELP[]="Yes, No, or Quit? ";
char M_REV_OS_FMT[]="%3d %-8s ";
char M_FILENAME_FORM[]="%s\n";
char M_BRIEF_LIST_SEPARATOR[]="------------ ---------- ---------- -----\n";
char M_SHORT_NAME_FMT[]="%-12s ";
char M_ARJDISP_INVOCATION[]="%s %s %s %ld %ld %ld %c";
char M_DECODE_CRIT_ERROR[]="Crit error\n";
char M_DECODE_EOF[]="EOF\n";
char M_DAMAGED_SEC_ARCHIVE[]="\n*** Damaged ARJ-SECURED archive!";
char M_DAMAGED_SFX[]="Damaged self-extractor. Could be virus damage.";
char M_CONTINUE_EXTRACTION[]="\nContinue extraction? ";
char M_QUERY_DEST_DIR[]="\nOK to install to directory %s ? ";
char M_ENTER_INSTALL_DIR[]="\nEnter the install directory (blank = current): ";
char M_ARJSFX_BANNER[]="ARJSFX 3.10 - ARJ Archive Self-Extractor. %s -? for help.\nCopyright (c) 1998-2004 ARJ Software Russia. All Rights Reserved.\n\n";
char M_SW_TABLE[]="ELTVXABCDFGIJKMNOPSUWY*?H!";
char M_ARCHIVE_CREATED[]="Archive date      : %s\n";
char M_NO_PWD_OPTION[]="Password missing";
char M_ARGTABLE_OVERFLOW[]="Too many arguments";
char M_VALID_ARJSEC[]="\n*** Valid ARJ-SECURITY envelope signature:\n*** %s\n";
char M_BAD_HEADER[]="Bad archive header";
char M_INVALID_SWITCH[]="Bad switch or command: %c\n\n";
char M_BADTABLE[]="Bad file data";
char M_BADTABLE_G[]="Bad file data or bad password";
char M_CANTREAD[]="Can't read file!  Damaged file?";
char M_DISK_FULL[]="Can't write file!  Disk full?";
char M_CRC_ERROR[]="Data error!\n";
char M_OK[]="OK   \n";
char M_FOREIGN_BINARY[]=", Binary file from another OS!\n";
char M_FILE_IS_GARBLED[]="File is encrypted, ";
char M_EXTR_CMD_QUERY[]="\nOK to execute the command \"%s\"? ";
char M_EXECUTING_CMD[]="\nExecuting the command \"%s\".\n";
char M_EXTRACTING_1_TO_2[]="Extracting %-12s to %s";
char M_EXTRACTING[]="Extracting %s, ";
char M_EXISTS[]="%-12s exists, ";
char M_VLIST_HDR[]="Pathname/Comment\n";
char M_LIST_P2[]="  Original Compressed Ratio DateTime modified Attributes/GUA PMG\n";
char M_HEADER_CRC_ERROR[]="Header data error";
char M_IS_SAME_OR_NEWER[]="%-12s is same or newer, ";
char M_TOTAL_STATS[]=" %5d files %10ld %10ld %u.%03u\n";
char M_N_FILES[]=" %5d file(s)\n";
char M_NOT_EXISTS[]="%-12s does not exist, ";
char M_RAW_INPUT_REJECTED[]="Can't accept input in RAW mode.  Try /y switch.";
char M_TESTING[]="Testing %s, ";
char M_UNCOMPRESSING[]="Uncompressing ";
char M_UNSTORING[]="Unstoring     ";
char M_SFX_USAGE[]="Usage: ARJSFX [-command] [-switch(s)] [directory\\] [file(s)]\n";
char M_SFX_COMMANDS[]="\nCommands:\ne: Extract files                   v: Verbosely list contents\nl: List contents                   x: eXtract files with pathname (default)\nt: Test contents\n\nSwitches:\na: show ANSI comments              m: Make directories\nb: prompt for directory            n: only New files\nc: skip time stamp Check           o: Overwrite files\nd: display program option          p: match with Pathname\nf: Freshen existing files          s: skip virus/Security check\ng: unGarble with password          u: Update files\ni: no progress Indicator           w: skip extract prompt\nj: process Win95 archive           y: assume Yes on queries\nk: long extract messages           !: execute command option\n";
char M_STD_LIST_LINE[]="%10ld %10ld %u.%03u %s %14s %c%u%c\n";
char M_LIST_SEPARATOR[]="------------ ---------- ---------- ----- ----------------- -------------- ---\n";
char M_LONG_NAME_FMT[]="%-12s\n             ";
char M_VERBOSE_NAME_FMT[]="%-12s\n";

