/*
 * ./LINUX-GNU/EN/RS/IMSG_SFJ.C , 2024/05/29
 * ---------------------------------------------------------------------------
 * Do not modify this file. It is automatically generated by MSGBIND from
 * ./RESOURCE/RESOURCE.TXT.
 * To rebuild the language resources, run MSGBIND.
 *
 */

#include "bindings.h"
#include "environ.h"
#include "arjtypes.h"

#include "./linux-gnu/en/rs/msg_sfj.h"

FMSGP FARMSGS []={M_BAD_HEADER, M_BADTABLE, M_CANTREAD, M_DISK_FULL, M_ARJSFX_BANNER, 
                  M_HEADER_CRC_ERROR, M_SFXJR_TICKER, M_VD_SPACE, M_SKIPPED, M_FILE_EXISTS, M_CANTOPEN_F, 
                  M_EXTRACTING, M_OK, M_CRC_ERROR, M_INVALID_SWITCH, M_CANTOPEN, M_PROCESSING_ARCHIVE, 
                  M_EXTRACTED, M_FILES, M_BREAK_SIGNALED, M_FOUND_ERRORS, NULL};


