/*
 * ./LINUX-GNU/EN/RS/IMSG_REG.C , 2024/05/29
 * ---------------------------------------------------------------------------
 * Do not modify this file. It is automatically generated by MSGBIND from
 * ./RESOURCE/RESOURCE.TXT.
 * To rebuild the language resources, run MSGBIND.
 *
 */

#include "bindings.h"
#include "environ.h"
#include "arjtypes.h"

#include "./linux-gnu/en/rs/msg_reg.h"

FMSGP FARMSGS []={M_CANTOPEN, M_CANTREAD, M_CANT_SEEK, M_CANT_WRITE, M_REG_TOTALS, 
                  M_REG_FAILED, M_REGISTER_BANNER, M_PATCH_NOT_FOUND, M_REGISTER_STAMPED, 
                  M_VERIFY_REGISTRATION, M_MISSING_REG_FILE, M_REGISTER_HELP, M_IMPROPER_REG_FMT, NULL};


