/*
 * ./LINUX-GNU/EN/RS/IMSG_SFX.C , 2024/05/29
 * ---------------------------------------------------------------------------
 * Do not modify this file. It is automatically generated by MSGBIND from
 * ./RESOURCE/RESOURCE.TXT.
 * To rebuild the language resources, run MSGBIND.
 *
 */

#include "bindings.h"
#include "environ.h"
#include "arjtypes.h"

#include "./linux-gnu/en/rs/msg_sfx.h"

FMSGP FARMSGS []={M_VALID_ENVELOPE, M_VERIFYING_ARJSEC, M_BREAK_SIGNALED, M_SIGTERM, 
                  M_CANTOPEN, M_CANT_MKDIR, M_QUERY_CREATE_DIR, M_FOUND_N_ERRORS, M_VLIST_P1, 
                  M_LIST_P1, M_NO, M_OUT_OF_MEMORY, M_QUERY_OVERWRITE, M_PROCESSING_ARCHIVE, 
                  M_QUIT, M_N_BYTES, M_SKIPPED, M_YES, M_REPLIES_HELP, M_DAMAGED_SEC_ARCHIVE, 
                  M_DAMAGED_SFX, M_CONTINUE_EXTRACTION, M_QUERY_DEST_DIR, M_ENTER_INSTALL_DIR, 
                  M_ARJSFX_BANNER, M_SW_TABLE, M_ARCHIVE_CREATED, M_NO_PWD_OPTION, M_ARGTABLE_OVERFLOW, 
                  M_VALID_ARJSEC, M_BAD_HEADER, M_INVALID_SWITCH, M_BADTABLE, M_BADTABLE_G, M_CANTREAD, 
                  M_DISK_FULL, M_CRC_ERROR, M_OK, M_FOREIGN_BINARY, M_FILE_IS_GARBLED, 
                  M_EXTR_CMD_QUERY, M_EXECUTING_CMD, M_EXTRACTING_1_TO_2, M_EXTRACTING, M_EXISTS, 
                  M_VLIST_HDR, M_LIST_P2, M_HEADER_CRC_ERROR, M_IS_SAME_OR_NEWER, M_TOTAL_STATS, 
                  M_N_FILES, M_NOT_EXISTS, M_RAW_INPUT_REJECTED, M_TESTING, M_UNCOMPRESSING, 
                  M_UNSTORING, M_SFX_USAGE, M_SFX_COMMANDS, NULL};


