/*
 * ./LINUX-GNU/EN/RS/IMSG_ADI.C , 2024/05/29
 * ---------------------------------------------------------------------------
 * Do not modify this file. It is automatically generated by MSGBIND from
 * ./RESOURCE/RESOURCE.TXT.
 * To rebuild the language resources, run MSGBIND.
 *
 */

#include "bindings.h"
#include "environ.h"
#include "arjtypes.h"

#include "./linux-gnu/en/rs/msg_adi.h"

NMSGP ADIMSG []={M_ARJDISP_COPYRIGHT, M_ARJDISP_DISTRIBUTION, M_ARJDISP_LICENSE, 
                 M_PROCESSING_ARCHIVE, M_FINISHED_PROCESSING, M_ARJDISP_INFO, M_PRESS_ANY_KEY, 
                 M_EXTRACTING_FILE, M_PROCESSING_FILE, M_TESTING_FILE, M_ADDING_FILE, 
                 M_ARJDISP_CTR_START, M_ARJDISP_CTR, M_ARJDISP_BANNER, NULL};


