/*
 * ./LINUX-GNU/EN/RS/MSG_SFX.H  , 2024/05/29
 * ---------------------------------------------------------------------------
 * Do not modify this file. It is automatically generated by MSGBIND from
 * ./RESOURCE/RESOURCE.TXT.
 * To rebuild the language resources, run MSGBIND.
 *
 */

extern FMSG M_VALID_ENVELOPE[];
extern FMSG M_VERIFYING_ARJSEC[];
extern FMSG M_BREAK_SIGNALED[];
extern FMSG M_SIGTERM[];
extern FMSG M_CANTOPEN[];
extern FMSG M_CANT_MKDIR[];
extern FMSG M_QUERY_CREATE_DIR[];
extern FMSG M_FOUND_N_ERRORS[];
extern FMSG M_VLIST_P1[];
extern FMSG M_LIST_P1[];
extern FMSG M_NO[];
extern FMSG M_OUT_OF_MEMORY[];
extern FMSG M_QUERY_OVERWRITE[];
extern FMSG M_PROCESSING_ARCHIVE[];
extern FMSG M_QUIT[];
extern FMSG M_N_BYTES[];
extern FMSG M_SKIPPED[];
extern FMSG M_YES[];
extern FMSG M_REPLIES_HELP[];
extern FMSG M_REV_OS_FMT[];
extern FMSG M_FILENAME_FORM[];
extern FMSG M_BRIEF_LIST_SEPARATOR[];
extern FMSG M_SHORT_NAME_FMT[];
extern FMSG M_ARJDISP_INVOCATION[];
extern FMSG M_DECODE_CRIT_ERROR[];
extern FMSG M_DECODE_EOF[];
extern FMSG M_DAMAGED_SEC_ARCHIVE[];
extern FMSG M_DAMAGED_SFX[];
extern FMSG M_CONTINUE_EXTRACTION[];
extern FMSG M_QUERY_DEST_DIR[];
extern FMSG M_ENTER_INSTALL_DIR[];
extern FMSG M_ARJSFX_BANNER[];
extern FMSG M_SW_TABLE[];
extern FMSG M_ARCHIVE_CREATED[];
extern FMSG M_NO_PWD_OPTION[];
extern FMSG M_ARGTABLE_OVERFLOW[];
extern FMSG M_VALID_ARJSEC[];
extern FMSG M_BAD_HEADER[];
extern FMSG M_INVALID_SWITCH[];
extern FMSG M_BADTABLE[];
extern FMSG M_BADTABLE_G[];
extern FMSG M_CANTREAD[];
extern FMSG M_DISK_FULL[];
extern FMSG M_CRC_ERROR[];
extern FMSG M_OK[];
extern FMSG M_FOREIGN_BINARY[];
extern FMSG M_FILE_IS_GARBLED[];
extern FMSG M_EXTR_CMD_QUERY[];
extern FMSG M_EXECUTING_CMD[];
extern FMSG M_EXTRACTING_1_TO_2[];
extern FMSG M_EXTRACTING[];
extern FMSG M_EXISTS[];
extern FMSG M_VLIST_HDR[];
extern FMSG M_LIST_P2[];
extern FMSG M_HEADER_CRC_ERROR[];
extern FMSG M_IS_SAME_OR_NEWER[];
extern FMSG M_TOTAL_STATS[];
extern FMSG M_N_FILES[];
extern FMSG M_NOT_EXISTS[];
extern FMSG M_RAW_INPUT_REJECTED[];
extern FMSG M_TESTING[];
extern FMSG M_UNCOMPRESSING[];
extern FMSG M_UNSTORING[];
extern FMSG M_SFX_USAGE[];
extern FMSG M_SFX_COMMANDS[];
extern FMSG M_STD_LIST_LINE[];
extern FMSG M_LIST_SEPARATOR[];
extern FMSG M_LONG_NAME_FMT[];
extern FMSG M_VERBOSE_NAME_FMT[];

#define FARMSGS_CRC32 0x51b2df2c
extern FMSGP FARMSGS[];

