/*
 * ./LINUX-GNU/EN/RS/MSG_ADI.H  , 2024/05/29
 * ---------------------------------------------------------------------------
 * Do not modify this file. It is automatically generated by MSGBIND from
 * ./RESOURCE/RESOURCE.TXT.
 * To rebuild the language resources, run MSGBIND.
 *
 */

extern char M_ARJDISP_COPYRIGHT[];
extern char M_ARJDISP_DISTRIBUTION[];
extern char M_ARJDISP_LICENSE[];
extern char M_PROCESSING_ARCHIVE[];
extern char M_FINISHED_PROCESSING[];
extern char M_ARJDISP_INFO[];
extern char M_PRESS_ANY_KEY[];
extern char M_EXTRACTING_FILE[];
extern char M_PROCESSING_FILE[];
extern char M_TESTING_FILE[];
extern char M_ADDING_FILE[];
extern char M_ARJDISP_CTR_START[];
extern char M_ARJDISP_CTR[];
extern char M_ARJDISP_BANNER[];

#define ADIMSG_CRC32 0xe05433a0
extern NMSGP ADIMSG[];

