/*
 * ./LINUX-GNU/EN/RS/MSG_STB.H  , 2024/05/29
 * ---------------------------------------------------------------------------
 * Do not modify this file. It is automatically generated by MSGBIND from
 * ./RESOURCE/RESOURCE.TXT.
 * To rebuild the language resources, run MSGBIND.
 *
 */

extern char M_SFXSTUB_BANNER[];
extern char M_SFXSTUB_BLURB_1[];
extern char M_SFXSTUB_BLURB_2[];


