/*
 * ./LINUX-GNU/EN/RS/MSG_REG.H  , 2024/05/29
 * ---------------------------------------------------------------------------
 * Do not modify this file. It is automatically generated by MSGBIND from
 * ./RESOURCE/RESOURCE.TXT.
 * To rebuild the language resources, run MSGBIND.
 *
 */

extern FMSG M_CANTOPEN[];
extern FMSG M_CANTREAD[];
extern FMSG M_CANT_SEEK[];
extern FMSG M_CANT_WRITE[];
extern FMSG M_REG_TOTALS[];
extern FMSG M_REG_FAILED[];
extern FMSG M_REGISTER_BANNER[];
extern FMSG M_PATCH_NOT_FOUND[];
extern FMSG M_REGISTER_STAMPED[];
extern FMSG M_VERIFY_REGISTRATION[];
extern FMSG M_MISSING_REG_FILE[];
extern FMSG M_REGISTER_HELP[];
extern FMSG M_IMPROPER_REG_FMT[];

#define FARMSGS_CRC32 0x2f4af9b7
extern FMSGP FARMSGS[];

