/*
 * ./LINUX-GNU/EN/RS/MSG_SFJ.H  , 2024/05/29
 * ---------------------------------------------------------------------------
 * Do not modify this file. It is automatically generated by MSGBIND from
 * ./RESOURCE/RESOURCE.TXT.
 * To rebuild the language resources, run MSGBIND.
 *
 */

extern FMSG M_BAD_HEADER[];
extern FMSG M_BADTABLE[];
extern FMSG M_CANTREAD[];
extern FMSG M_DISK_FULL[];
extern FMSG M_ARJSFX_BANNER[];
extern FMSG M_HEADER_CRC_ERROR[];
extern FMSG M_SFXJR_TICKER[];
extern FMSG M_VD_SPACE[];
extern FMSG M_SKIPPED[];
extern FMSG M_FILE_EXISTS[];
extern FMSG M_CANTOPEN_F[];
extern FMSG M_EXTRACTING[];
extern FMSG M_OK[];
extern FMSG M_CRC_ERROR[];
extern FMSG M_INVALID_SWITCH[];
extern FMSG M_CANTOPEN[];
extern FMSG M_PROCESSING_ARCHIVE[];
extern FMSG M_EXTRACTED[];
extern FMSG M_FILES[];
extern FMSG M_BREAK_SIGNALED[];
extern FMSG M_FOUND_ERRORS[];

#define FARMSGS_CRC32 0xcf7046ae
extern FMSGP FARMSGS[];

