/*
 * ./LINUX-GNU/EN/RS/NMSG_STB.C , 2024/05/29
 * ---------------------------------------------------------------------------
 * Do not modify this file. It is automatically generated by MSGBIND from
 * ./RESOURCE/RESOURCE.TXT.
 * To rebuild the language resources, run MSGBIND.
 *
 */

#include "bindings.h"
#include "environ.h"
#include "arjtypes.h"

char M_SFXSTUB_BANNER[]="ARJ SFXSTUB 1.02 - (c) 1999-2004, ARJ Software Russia.\n\n";
char M_SFXSTUB_BLURB_1[]="This EXE file is part of an ARJ multiple volume archive.  Executing\n";
char M_SFXSTUB_BLURB_2[]="the first volume of this series will extract all of the ARJ volumes.\n";

