/*
 * ./LINUX-GNU/EN/RS/NMSG_REJ.C , 2024/05/29
 * ---------------------------------------------------------------------------
 * Do not modify this file. It is automatically generated by MSGBIND from
 * ./RESOURCE/RESOURCE.TXT.
 * To rebuild the language resources, run MSGBIND.
 *
 */

#include "bindings.h"
#include "environ.h"
#include "arjtypes.h"

char M_LOGENTRY_MARKER[]="%02d:%02d:%02d %3s %s\n";
char M_LOGENTRY_HEADER[]="%02d:%02d:%02d %3s   Old size   New size    Savings Original name\n";
char M_LOGENTRY_SKIP[]="%02d:%02d:%02d %3s SKIP                  %10d %s\n";
char M_LOGENTRY_CONV[]="%02d:%02d:%02d %3s %10ld %10ld %10ld %s\n";
char M_LOGENTRY_FOOTER[]="%02d:%02d:%02d %3s %10ld %10ld %10ld %10ld seconds\n";

