/*
 * ./LINUX-GNU/EN/RS/NMSG_ADI.C , 2024/05/29
 * ---------------------------------------------------------------------------
 * Do not modify this file. It is automatically generated by MSGBIND from
 * ./RESOURCE/RESOURCE.TXT.
 * To rebuild the language resources, run MSGBIND.
 *
 */

#include "bindings.h"
#include "environ.h"
#include "arjtypes.h"

char M_ARJDISP_COPYRIGHT[]="ARJ Demonstration Display Program 1.10 (c) 2004, ARJ Software Russia.";
char M_ARJDISP_DISTRIBUTION[]="May only be distributed with the full ARJ software package.";
char M_ARJDISP_LICENSE[]="This program is subject of GNU General Public License.";
char M_PROCESSING_ARCHIVE[]="Processing archive: %s";
char M_FINISHED_PROCESSING[]="Finished processing archive: %s";
char M_ARJDISP_INFO[]="This is a demonstration program showing a new feature of ARJ\nthat allows a programmer to build a graphical-like interface\naround the ARJ, DEARJ, or ARJSFX programs. Installation programs\nusing ARJ will look more professional.\n";
char M_PRESS_ANY_KEY[]="Press any key to continue: ";
char M_EXTRACTING_FILE[]="Extracting file   : %s";
char M_PROCESSING_FILE[]="Processing file   : %s";
char M_TESTING_FILE[]="Testing file      : %s";
char M_ADDING_FILE[]="Adding file       : %s";
char M_ARJDISP_CTR_START[]="0 percent complete";
char M_ARJDISP_CTR[]="%3d percent complete";
char M_ARJDISP_BANNER[]="Usage: arjdisp arg1 arg2 arg3 arg4 arg5 arg6";

